package net.irisshaders.iris.pipeline.description;

public enum BindingInstallerKind {
	IRIS_SAMPLERS_RENDER_TARGETS,
	IRIS_SAMPLERS_CUSTOM_TEXTURES,
	IRIS_SAMPLERS_CUSTOM_IMAGES,
	IRIS_SAMPLERS_NOISE,
	IRIS_SAMPLERS_COMPOSITE_DEPTH,
	IRIS_SAMPLERS_WORLD_DEPTH,
	IRIS_SAMPLERS_LEVEL,
	IRIS_SAMPLERS_PBR_DETECTION,
	IRIS_SAMPLERS_SHADOW,
	IRIS_SAMPLERS_CENTER_DEPTH,
	IRIS_IMAGES_RENDER_TARGETS,
	IRIS_IMAGES_CUSTOM_IMAGES,
	IRIS_IMAGES_SHADOW_COLOR,
	SHADER_STORAGE_BUFFER_HOLDER,
	COMPATIBILITY_RESOURCE
}
