package net.irisshaders.iris.pipeline;

public enum ExternalDrawSelectorPolicy {
	STATIC_SHADER_KEY,
	ENTITY_CUTOUT,
	ENTITY_TRANSLUCENT,
	ENTITY_SOLID,
	TEXT,
	TEXT_INTENSITY,
	SHADOW_SHADER_KEY,
	SODIUM_TERRAIN_SOLID,
	SODIUM_TERRAIN_CUTOUT,
	SODIUM_TERRAIN_TRANSLUCENT,
	SHADOW_SODIUM_TERRAIN_SOLID,
	SHADOW_SODIUM_TERRAIN_CUTOUT,
	SHADOW_SODIUM_TERRAIN_TRANSLUCENT,
	HAND_CUTOUT,
	HAND_CUTOUT_DIFFUSE,
	HAND_TEXT,
	HAND_TEXT_TRANSLUCENT,
	HAND_TRANSLUCENT,
	HAND_WATER_DIFFUSE,
	BLOCK_ENTITY_DIFFUSE,
	BLOCK_ENTITY_TRANSLUCENT,
	BLOCK_ENTITY_TEXT,
	BLOCK_ENTITY_TEXT_INTENSITY
}
