package net.irisshaders.iris.pipeline;

public enum ExternalDrawRuntimeDependency {
	WORLD_RENDERING_PHASE,
	SHADOW_RENDERING_STATE,
	HAND_RENDERER,
	RENDER_PIPELINE_NAMESPACE,
	RENDER_PIPELINE_SHADER_DEFINES,
	RENDER_PIPELINE_BLEND_FUNCTION
}
